server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:8080/eureka/,http://www.eureka2.com:8081/eureka/
    register-with-eureka: false
spring:
  application:
    name: zuul10000
#配置zuul的路由匹配规则
zuul:
  routes:
    test1:
      path: /test1/**
#可小写CONSUMER-FEIGN
      serviceId: consumer-feign
    test2:
      path: /test2/**
      serviceId: consumer-ribbon